# jekyll configuration

title: "Jekyll-asciidoc-quickstart"

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

asciidoc_ext: txt

# end of configuration
