# jekyll configuration

title: "Jekyll-asciidoc-quickstart"

exclude: [ 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README' ]

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

asciidoc_ext: txt

# end of configuration
